
[env]
TERM = "xterm-256color"

[colors.primary]
background = "#000000" 

[font]
size = 11.5
normal.family = "JetBrainsMonoNL Nerd Font Mono"

[window]
padding.x = 5
padding.y = 5

[mouse]
hide_when_typing = true

