

[env]
TERM = "xterm-256color"

[font]
size = 13.3

[window]
padding.x = 5
padding.y = 5

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
      { key = "Tab", mods = "Super", action = "ToggleViMode"}
]

